//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerFirstProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerFirstProject.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full History and Directors.
        /// </summary>
        public static string AboutGhibliPreviewButton {
            get {
                return ResourceManager.GetString("AboutGhibliPreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Ghibli is a renowned Japanese animation studio, known for its poetic, visually striking, and emotionally profound films. Founded in 1985 by animation masters Hayao Miyazaki and Isao Takahata, with production by Toshio Suzuki and financial support from Yasuyoshi Tokuma, the studio quickly became a global reference in auteur animation. Its works blend human themes, nature, fantasy, and social commentary, resonating with generations around the world..
        /// </summary>
        public static string AboutGhibliPreviewText {
            get {
                return ResourceManager.GetString("AboutGhibliPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Studio Ghibli.
        /// </summary>
        public static string AboutGhibliPreviewTitle {
            get {
                return ResourceManager.GetString("AboutGhibliPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option above..
        /// </summary>
        public static string AboutSectionGenericText {
            get {
                return ResourceManager.GetString("AboutSectionGenericText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More About Me.
        /// </summary>
        public static string AboutSectionMeButton {
            get {
                return ResourceManager.GetString("AboutSectionMeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET developer focused on ASP.NET Core, Blazor, and clean architectures, passionate about turning ideas into well-structured, reliable digital experiences. I have hands-on experience with professional, academic and personal projects covering both back-end and front-end development, always emphasizing good practices, organization, and usability. I’m continuously expanding my skills by exploring technologies like .NET MAUI, React, Azure, and databases such as SQL Server and MySQL. Beyond technical proficiency [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutSectionMeText {
            get {
                return ResourceManager.GetString("AboutSectionMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string AboutSectionMeTitle {
            get {
                return ResourceManager.GetString("AboutSectionMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Project&apos;s Complete Tech Stack.
        /// </summary>
        public static string AboutSectionProjectButton {
            get {
                return ResourceManager.GetString("AboutSectionProjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-end project developed with Blazor Server, designed to enhance practical skills and serve as a professional portfolio piece. The application explores UI/UX design principles, emphasizing clean structure, component reusability, and full responsiveness. Inspired by the magical universe of Studio Ghibli’s films, the project aims to capture the studio’s distinctive atmosphere and visual storytelling through a smooth, elegant, and user-friendly interface — blending minimalist design with cosiness..
        /// </summary>
        public static string AboutSectionProjectText {
            get {
                return ResourceManager.GetString("AboutSectionProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Project.
        /// </summary>
        public static string AboutSectionProjectTitle {
            get {
                return ResourceManager.GetString("AboutSectionProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutSectionTitle {
            get {
                return ResourceManager.GetString("AboutSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore All Movies.
        /// </summary>
        public static string AwardsSectionButton {
            get {
                return ResourceManager.GetString("AwardsSectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Winning Works.
        /// </summary>
        public static string AwardsSectionTitle {
            get {
                return ResourceManager.GetString("AwardsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string FooterCookiesButton {
            get {
                return ResourceManager.GetString("FooterCookiesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string FooterCopyrightButton {
            get {
                return ResourceManager.GetString("FooterCopyrightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 João Vitor Ventura..
        /// </summary>
        public static string FooterCopyrightText {
            get {
                return ResourceManager.GetString("FooterCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website was developed by .
        /// </summary>
        public static string FooterDisclaimerPart1 {
            get {
                return ResourceManager.GetString("FooterDisclaimerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to João Vitor Ventura.
        /// </summary>
        public static string FooterDisclaimerPart2 {
            get {
                return ResourceManager.GetString("FooterDisclaimerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for educational purposes. It uses data from the .
        /// </summary>
        public static string FooterDisclaimerPart3 {
            get {
                return ResourceManager.GetString("FooterDisclaimerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Ghibli API.
        /// </summary>
        public static string FooterDisclaimerPart4 {
            get {
                return ResourceManager.GetString("FooterDisclaimerPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , which is not affiliated with Studio Ghibli. Neither this site nor the API claims any rights to Studio Ghibli’s intellectual property. .
        /// </summary>
        public static string FooterDisclaimerPart5 {
            get {
                return ResourceManager.GetString("FooterDisclaimerPart5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string FooterPrivacyPolicyButton {
            get {
                return ResourceManager.GetString("FooterPrivacyPolicyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two siblings struggle to survive amidst war-torn Japan, in this heartbreaking and critically acclaimed masterpiece..
        /// </summary>
        public static string GraveOfTheFirefliesPreviewDescription {
            get {
                return ResourceManager.GetString("GraveOfTheFirefliesPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grave of the Fireflies.
        /// </summary>
        public static string GraveOfTheFirefliesTitle {
            get {
                return ResourceManager.GetString("GraveOfTheFirefliesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayao Miyazaki.
        /// </summary>
        public static string HayaoMiyazaki {
            get {
                return ResourceManager.GetString("HayaoMiyazaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More About Ghibli.
        /// </summary>
        public static string HeroButton {
            get {
                return ResourceManager.GetString("HeroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Fan Tribute to.
        /// </summary>
        public static string HeroFanTribute {
            get {
                return ResourceManager.GetString("HeroFanTribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made By Ventura.
        /// </summary>
        public static string HeroMadeBy {
            get {
                return ResourceManager.GetString("HeroMadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isao Takahata.
        /// </summary>
        public static string IsaoTakahata {
            get {
                return ResourceManager.GetString("IsaoTakahata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two sisters move to the countryside and encounter gentle forest spirits, in this beloved and enchanting Studio Ghibli classic..
        /// </summary>
        public static string MyNeighborTotoroPreviewDescription {
            get {
                return ResourceManager.GetString("MyNeighborTotoroPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Neighbor Totoro.
        /// </summary>
        public static string MyNeighborTotoroTitle {
            get {
                return ResourceManager.GetString("MyNeighborTotoroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string NavAboutme {
            get {
                return ResourceManager.GetString("NavAboutme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Portfolio.
        /// </summary>
        public static string NavAboutmeMyPortfolio {
            get {
                return ResourceManager.GetString("NavAboutmeMyPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Resume.
        /// </summary>
        public static string NavAboutmeMyResume {
            get {
                return ResourceManager.GetString("NavAboutmeMyResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Stack.
        /// </summary>
        public static string NavAboutmeTechStack {
            get {
                return ResourceManager.GetString("NavAboutmeTechStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Am I.
        /// </summary>
        public static string NavAboutmeWhoAmI {
            get {
                return ResourceManager.GetString("NavAboutmeWhoAmI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string NavContact {
            get {
                return ResourceManager.GetString("NavContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        public static string NavFilms {
            get {
                return ResourceManager.GetString("NavFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string NavFilmsCharacters {
            get {
                return ResourceManager.GetString("NavFilmsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmography.
        /// </summary>
        public static string NavFilmsFilmography {
            get {
                return ResourceManager.GetString("NavFilmsFilmography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string NavFilmsOthers {
            get {
                return ResourceManager.GetString("NavFilmsOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Ghibli.
        /// </summary>
        public static string NavGhibli {
            get {
                return ResourceManager.GetString("NavGhibli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notable Figures.
        /// </summary>
        public static string NavGhibliFigures {
            get {
                return ResourceManager.GetString("NavGhibliFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghibli&apos;s History.
        /// </summary>
        public static string NavGhibliHistory {
            get {
                return ResourceManager.GetString("NavGhibliHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string NavThemeDark {
            get {
                return ResourceManager.GetString("NavThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string NavThemeLight {
            get {
                return ResourceManager.GetString("NavThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string NavThemeSystem {
            get {
                return ResourceManager.GetString("NavThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A warrior cursed by a deadly spirit is drawn into a fierce struggle between humans and the gods of the forest in this award-winning epic..
        /// </summary>
        public static string PrincessMononokePreviewDescription {
            get {
                return ResourceManager.GetString("PrincessMononokePreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Princess Mononoke.
        /// </summary>
        public static string PrincessMononokeTitle {
            get {
                return ResourceManager.GetString("PrincessMononokeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayao Miyazaki.
        /// </summary>
        public static string QuoteAuthor {
            get {
                return ResourceManager.GetString("QuoteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I would like to make a film to tell children &apos;it&apos;s good to be alive&apos;.&quot;.
        /// </summary>
        public static string QuotePhrase {
            get {
                return ResourceManager.GetString("QuotePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files/JoaoVitorVenturaResumeEnglish.pdf.
        /// </summary>
        public static string ResumePath {
            get {
                return ResourceManager.GetString("ResumePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A young girl enters a magical world ruled by gods, witches, and spirits, and must save her parents in this Oscar-winning masterpiece..
        /// </summary>
        public static string SpiritedAwayPreviewDescription {
            get {
                return ResourceManager.GetString("SpiritedAwayPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirited Away.
        /// </summary>
        public static string SpiritedAwayTitle {
            get {
                return ResourceManager.GetString("SpiritedAwayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boy grieving his mother discovers a hidden world guided by a mysterious heron, in Hayao Miyazaki’s Academy Award–winning tale of loss and wonder..
        /// </summary>
        public static string TheBoyAndTheHeronPreviewDescription {
            get {
                return ResourceManager.GetString("TheBoyAndTheHeronPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Boy and the Heron.
        /// </summary>
        public static string TheBoyAndTheHeronTitle {
            get {
                return ResourceManager.GetString("TheBoyAndTheHeronTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toshio Suzuki.
        /// </summary>
        public static string ToshioSuzuki {
            get {
                return ResourceManager.GetString("ToshioSuzuki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yasuyoshi Tokuma.
        /// </summary>
        public static string YasuyoshiTokuma {
            get {
                return ResourceManager.GetString("YasuyoshiTokuma", resourceCulture);
            }
        }
    }
}
